name: 'Build cfssl docker image'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions: 
  packages: write

on:
  schedule:
    - cron: 30 14 * * SAT
  push:
    branches:
      - main
    paths:
      - cfssl/**
  pull_request:
    branches:
      - main
    paths:
      - cfssl/**
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-image:
    name: 'Build cfssl docker image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (cfssl)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./cfssl
          target: cfssl
          file: ./cfssl/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/meggernet/docker/cfssl:latest,ghcr.io/meggernet/docker/cfssl:1.6
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: Build and push (cfssl)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./cfssl
          target: cfssl-server
          file: ./cfssl/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/meggernet/docker/cfssl-server:latest,ghcr.io/meggernet/docker/cfssl:1.6
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max

