name: 'Build nginx docker image'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions: 
  packages: write

on:
  schedule:
    - cron: 0 7 * * THU
  push:
    branches:
      - main
    paths:
      - nginx/**
  pull_request:
    branches:
      - main
    paths:
      - nginx/**
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-image:
    name: 'Build nginx docker image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version from Dockerfile
        id: docker
        run: echo "version=$(./extract-version.sh ./nginx/Dockerfile)" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (nginx)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./nginx
          target: nginx
          file: ./nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/meggernet/docker/nginx:latest,ghcr.io/meggernet/docker/nginx:${{ steps.docker.outputs.version }},ghcr.io/meggernet/docker/proxy:${{ steps.docker.outputs.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (nginx)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./nginx
          target: styleguide
          file: ./nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/meggernet/docker/styleguide:latest,ghcr.io/meggernet/docker/styleguide:${{ steps.docker.outputs.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

